<a href="https://colab.research.google.com/github/akv2011/DL-And-ML/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
tensor_zero_df=tf.constant(4)
print(tensor_zero_df)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_df=tf.constant([2,0,-3,8,90])
print(tensor_one_df)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [ ]:
tensor_one_df=tf.constant([2,0.4,-3,8.,9.0,0.],dtype=tf.float32)
cast_tensor_df=tf.cast(tensor_one_df,dtype=tf.int16)
cast1_tensor_df=tf.cast(tensor_one_df,dtype=tf.bool)
print(tensor_one_df)
print(cast_tensor_df)
print(cast1_tensor_df)

tf.Tensor([ 2.   0.4 -3.   8.   9.   0. ], shape=(6,), dtype=float32)
tf.Tensor([ 2  0 -3  8  9  0], shape=(6,), dtype=int16)
tf.Tensor([ True  True  True  True  True False], shape=(6,), dtype=bool)


In [ ]:
tensor_two_df=tf.constant([
    [2,3,45],
    [44,5,674],
    [4,554,66]
])
print(tensor_two_df)

tf.Tensor(
[[  2   3  45]
 [ 44   5 674]
 [  4 554  66]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_df=tf.constant([

[[ 2,3 ,45],
[ 44 ,5 ,674]],

[[  4 ,554,  66],
 [4,645,3]],

[[4,6,3],
 [4,556,4]],

 [[44,3,3],
  [45,54,3]]

 ])
print(tensor_three_df)


tf.Tensor(
[[[  2   3  45]
  [ 44   5 674]]

 [[  4 554  66]
  [  4 645   3]]

 [[  4   6   3]
  [  4 556   4]]

 [[ 44   3   3]
  [ 45  54   3]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_df.shape
      )

(4, 2, 3)


In [ ]:
print(tensor_three_df.ndim)

3


In [ ]:
tensor_four_df=tf.constant([

[[[ 2,3 ,45],
[ 44 ,5 ,674]],

[[  4 ,554,  66],
 [4,645,3]],

[[4,6,3],
 [4,556,4]],

 [[44,3,3],
  [45,54,3]]],



[[[12,3 ,45],
[ 44 ,45 ,674]],

[[44 ,54,  66],
 [4,65,3]],

[[4,46,3],
 [4,56,4]],

 [[4,3,3],
  [5,4,3]]],



[[[72,43 ,45],
[ 7 ,45 ,674]],

[[7 ,54,  66],
 [4,5,3]],

[[414,46,3],
 [4,56,4]],

 [[44,3,3],
  [5,4,3]]],

  ])

print(tensor_four_df)

tf.Tensor(
[[[[  2   3  45]
   [ 44   5 674]]

  [[  4 554  66]
   [  4 645   3]]

  [[  4   6   3]
   [  4 556   4]]

  [[ 44   3   3]
   [ 45  54   3]]]


 [[[ 12   3  45]
   [ 44  45 674]]

  [[ 44  54  66]
   [  4  65   3]]

  [[  4  46   3]
   [  4  56   4]]

  [[  4   3   3]
   [  5   4   3]]]


 [[[ 72  43  45]
   [  7  45 674]]

  [[  7  54  66]
   [  4   5   3]]

  [[414  46   3]
   [  4  56   4]]

  [[ 44   3   3]
   [  5   4   3]]]], shape=(3, 4, 2, 3), dtype=int32)


 shape=(3, 4, 2, 3)

 Shape is from Row To column read from down

 int32
 can i use int 16 but memory allocation will be less ..thsu in  memory constraint tensors use lower precison.

In [ ]:
tensor_bool=tf.constant([True,False,True])
print(tensor_bool)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [ ]:
tensor_string=tf.constant(["hello world","hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


**Numpy To Tensor**

In [ ]:
import numpy as np
np_array=np.array([1,2,3,4])
print(np_array)


[1 2 3 4]


In [ ]:
converted_tensor=tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [56]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)
print(3*eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [57]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)
