<a href="https://colab.research.google.com/github/akv2011/DL-And-ML/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
tensor_zero_df=tf.constant(4)
print(tensor_zero_df)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_df=tf.constant([2,0,-3,8,90])
print(tensor_one_df)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [ ]:
tensor_two_df=tf.constant([
    [2,3,45],
    [44,5,674],
    [4,554,66]
])
print(tensor_two_df)

tf.Tensor(
[[  2   3  45]
 [ 44   5 674]
 [  4 554  66]], shape=(3, 3), dtype=int32)


In [33]:
tensor_three_df=tf.constant([

[[ 2,3 ,45],
[ 44 ,5 ,674]],

[[  4 ,554,  66],
 [4,645,3]],

[[4,6,3],
 [4,556,4]],

 [[44,3,3],
  [45,54,3]]

 ])
print(tensor_three_df)


tf.Tensor(
[[[  2   3  45]
  [ 44   5 674]]

 [[  4 554  66]
  [  4 645   3]]

 [[  4   6   3]
  [  4 556   4]]

 [[ 44   3   3]
  [ 45  54   3]]], shape=(4, 2, 3), dtype=int32)


In [35]:
print(tensor_three_df.shape
      )

(4, 2, 3)


In [36]:
print(tensor_three_df.ndim)

3


In [37]:
tensor_four_df=tf.constant([

[[[ 2,3 ,45],
[ 44 ,5 ,674]],

[[  4 ,554,  66],
 [4,645,3]],

[[4,6,3],
 [4,556,4]],

 [[44,3,3],
  [45,54,3]]],



[[[12,3 ,45],
[ 44 ,45 ,674]],

[[44 ,54,  66],
 [4,65,3]],

[[4,46,3],
 [4,56,4]],

 [[4,3,3],
  [5,4,3]]],



[[[72,43 ,45],
[ 7 ,45 ,674]],

[[7 ,54,  66],
 [4,5,3]],

[[414,46,3],
 [4,56,4]],

 [[44,3,3],
  [5,4,3]]],

  ])

print(tensor_four_df)

tf.Tensor(
[[[[  2   3  45]
   [ 44   5 674]]

  [[  4 554  66]
   [  4 645   3]]

  [[  4   6   3]
   [  4 556   4]]

  [[ 44   3   3]
   [ 45  54   3]]]


 [[[ 12   3  45]
   [ 44  45 674]]

  [[ 44  54  66]
   [  4  65   3]]

  [[  4  46   3]
   [  4  56   4]]

  [[  4   3   3]
   [  5   4   3]]]


 [[[ 72  43  45]
   [  7  45 674]]

  [[  7  54  66]
   [  4   5   3]]

  [[414  46   3]
   [  4  56   4]]

  [[ 44   3   3]
   [  5   4   3]]]], shape=(3, 4, 2, 3), dtype=int32)


 shape=(3, 4, 2, 3)

 Shape is from Row To column read from down