<a href="https://colab.research.google.com/github/akv2011/DL-And-ML/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
tensor_zero_df=tf.constant(4)
print(tensor_zero_df)

tf.Tensor(4, shape=(), dtype=int32)


In [20]:
tensor_one_df=tf.constant([2,0,-3,8,90])
print(tensor_one_df)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [23]:
tensor_two_df=tf.constant([
    [2,3,45],
    [44,5,674],
    [4,554,66]
])
print(tensor_two_df)

tf.Tensor(
[[  2   3  45]
 [ 44   5 674]
 [  4 554  66]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_df=tf.constant([

])